services:
  postgres:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - novus-network

  backend:
    image: ghcr.io/pavan-srikar/novus-backend:latest
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}

      GROQ_API_KEY: ${GROQ_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}

    ports:
      - "5000:5000"

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - novus-network

  frontend:
    image: ghcr.io/pavan-srikar/novus-frontend:latest
    restart: unless-stopped

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "80:80"

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - novus-network

volumes:
  postgres_data:

networks:
  novus-network:
    driver: bridge