apiVersion: v1
kind: Secret

metadata:
  name: novus-secret
  namespace: novus

type: Opaque

stringData:
  POSTGRES_USER: pavan
  POSTGRES_PASSWORD: pavan123
  POSTGRES_DB: novus

  DATABASE_URL: postgresql://pavan:pavan123@postgres:5432/novus

  JWT_SECRET: CHANGE_ME

  GROQ_API_KEY: ""
  GEMINI_API_KEY: ""
  OPENROUTER_API_KEY: ""
  DEEPSEEK_API_KEY: ""